# Configuration for Travis CI
language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - os: osx
      rust: stable
    - os: osx
      rust: nightly
  allow_failures:
    - rust: stable
    - rust: beta

# Dependencies for kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

# Install coverage tool
before_script:
- |
  if [[ $TRAVIS_OS_NAME == "linux" ]]; then
  cargo install cargo-travis &&
  export PATH=$HOME/.cargo/bin:$PATH;
  fi

# Main build
script:
- |
  cargo build &&
  cargo test &&
  cargo run --example example &&
  cargo run --example minimal &&
  cargo bench &&
  cargo doc

# Measure coverage, and upload to coveralls
after_success:
- if [[ $TRAVIS_OS_NAME == "linux" ]]; then cargo coveralls; fi
