# Configuration for Travis CI
language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - os: osx
      rust: stable

# Dependencies for kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

# Install coverage tool
before_script:
- |
  cargo install cargo-travis &&
  export PATH=$HOME/.cargo/bin:$PATH

# Main build
script:
- |
  cargo build &&
  cargo test &&
  cargo bench &&
  cargo doc

# Measure coverage, and upload to coveralls
after_success:
- cargo coveralls
