# Configuration for Travis CI
language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - os: osx
      rust: stable

# Documentation generation, and coverage data
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo --only stable doc; fi
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo --only stable doc-upload; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo coveralls --no-sudo --verify; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/version*compare-*; fi
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=dev
