# Configuration for Travis CI
language: rust
sudo: required
rust:
  - stable
  - beta
  - nightly

# Dependencies for coverage
addons:
  apt:
    packages:
      - libssl-dev

# Main build
script:
  - cargo clean
  - cargo build
  - cargo test
  - cargo run --example example
  - cargo run --example minimal
  - cargo bench
  - cargo doc

# Measure coverage, and upload to coveralls
after_success: |
  bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
